config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]
  

end

app/models/message.rb
class Message < ActiveRecord::Base
  # 名前は必須入力かつ20文字以内
  validates :name , length: { maximum: 20 } , presence: true
  # 内容は必須入力かつ2文字以上30文字以下(文字数でチェック)
  validates :body , length: { minimum: 2, maximum: 30 } , presence: true
  # validates :age , numericality: { only_integer: true , greater_than_or_equal_to: 0}, length: { maximum: 3 }
  validates :age , numericality: { only_integer: true , greater_than_or_equal_to: 0}, allow_blank:true, length: { maximum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  # edit,updateメソッドの前にset_messageを実行  
  before_action :set_message, only: [:edit, :update, :destroy]

  def index
    # 初期化
    @message = Message.new
    # 一覧の取得
    @messages = Message.all
  end

  def create
    # リクエストパラメータを取得して、DBに登録
    @message = Message.new(message_params)

      # コミット
    if @message.save
      redirect_to root_path , notice: 'メッセージを保存しました'
    else
      # メッセージが保存できなかった時
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'index'
    end
  end

  def edit
  end

  def update

    if @message.update(message_params)
      redirect_to root_path , notice: 'メッセージを保存しました'
      
      # 自分の画面にメッセージを正常終了するメッセージを表示
      # flash.now[:notice] = "メッセージを保存しました"
      # render 'edit'

    else
      # メッセージが保存できなかった時
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'edit'
    end

  end

  def destroy
    # リクエストパラメータを取得して、DBに登録
    @message.destroy

    redirect_to root_path , notice: 'メッセージを削除しました'

  end

  private

  # Rails4からStrongParamaterと呼ばれる機能が追加
  # セキュリティのため、permitメソッドで許可したパラメータ名しか取得できない
  def message_params
    params.require(:message).permit(:name, :body, :age)
  end

  def set_message
    @message = Message.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>MessageBoard</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Message Board</a>
      </div>
    </div>
  </nav>
  <div class="container">
    <%# フラッシュメッセージ %>
    <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>

</html>

app/views/messages/_form.html.erb
<%= form_for @message, html: {class: 'form-horizontal'} do |f| %>
  <% if @message.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <% @message.errors.full_messages.each do |full_message| %>
          <li>
            <%= full_message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <label class="col-sm-1 control-label">名前</label>
    <div class="col-sm-11">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-1 control-label">内容</label>
    <div class="col-sm-11">
      <%= f.text_area :body , size: "50x3", class: "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <label class="col-sm-1 control-label">年齢</label>
    <div class="col-sm-11">
      <%= f.text_field :age, class: "form-control" %>
    </div>
  </div>

  <br>
  <%= f.submit class:"btn btn-sm btn-primary" %>
<% end %>

app/views/messages/edit.html.erb
<h1>メッセージの編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    メッセージ一覧
  </div>
  <div class="panel-body">
    <% if @messages.size == 0 then %>
      メッセージ一覧はありません。
    <% else %>
      <% @messages.each do |message| %>
      <p>
        <span class="label label-info"><%= message.name %></span>
        <% if message.age == nil then %>
          <span class="label label-primary">未設定</span>
        <% else %>
          <span class="label label-primary"><%= message.age %>歳</span>
        <% end %>
        <%= simple_format(h(message.body)) %>
        (
        <%= link_to "edit" , edit_message_path(message) %> , 
        <%= link_to "destroy" , message , method: :delete, data: { confirm: '削除してもよろしいですか？' } %>
        )
      </p>
      <% end %>
    <% end %>
  </div>
</div>

<% #部分テンプレートを読み込んでいる %>
<%= render 'form' %>